impliedconsent.settings:
  type: config_object
  mapping:
    notice_text:
      type: string
      label: 'Notice text'
    notice_text_format:
      type: string
      label: 'Notice text format'
    confirm_text:
      type: string
      label: 'Confirm text'
    validate_by_click:
      type: boolean
      label: 'Validate by click'
    cookie_expires_in:
      type: integer
      label: 'Cookie expiry value in days'
    background_color:
      type: string
      label: 'CSS color of the background'
    text_color:
      type: string
      label: 'CSS color of the text'
    link_color:
      type: string
      label: 'CSS color of the link'
    button_background_color:
      type: string
      label: 'CSS color of the button background'
    button_color:
      type: string
      label: 'CSS color of the button'
    font_size:
      type: string
      label: 'CSS font-size'
    font_family:
      type: string
      label: 'CSS font-family'
